config/routes.rb
Rails.application.routes.draw do
  resources :words do
    resources :images
    resources :videos
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio.rb
class Audio < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :word
  has_one_attached :attachment, dependent: :destroy
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :word
  mount_uploader :attachment, AttachmentUploader
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :images, dependent: :destroy
  has_many :videos, dependent: :destroy
  has_many :audios, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :find_word, only: [:index, :create]
  before_action :set_image, only: [:show, :destroy]

  def index
    @images = @word.images.all
  end

  def show
  end

  def new
    @word = Word.find(params[:word_id])
    @image = Image.new(:word_id => params[:word_id])
  end

  def create
    @word.images.build(image_params.merge(revision: revision))

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: "New revision was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @images.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def find_word
      @word = Word.find(params[:word_id])
    end

    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:attachment)
    end

    def revision
      @word.images.count + 1
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :find_word, only: [:index, :create]
  before_action :set_video, only: [:show, :destroy]

  def index
    @videos = @word.videos.all
  end

  def show
  end

  def new
    @word = Word.find(params[:word_id])
    @video = Video.new(:word_id => params[:word_id])
  end

  def create
    @word.videos.build(video_params.merge(revision: revision))

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: "New revision was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @videos.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def find_word
      @word = Word.find(params[:word_id])
    end

    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:attachment)
    end

    def revision
      @word.videos.count + 1
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  def index
    @words = Word.all
  end

  def show
  end

  def new
    @word = Word.new
  end

  def edit
  end

  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: "Word was successfully created." }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: "Word was successfully updated." }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: "Word was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_word
      @word = Word.find(params[:id])
    end

    def word_params
      params.require(:word).permit(:wordform)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/images/_form.html.haml
= form_for [@word, @image] do |form|
  %p.text-left.h5
    = form.file_field :attachment
  .actions
    = form.submit

app/views/images/index.html.haml
%h1 Images
%table
  %thead
    %tr
      %th image
    %tbody
    - @images.each do |image|
      %tr
      %td= image_tag image.attachment
      %td= image.word.wordform
      %td= image.revision
%br/
= link_to "New Image", word_images_path

app/views/images/new.html.haml
%section
  %h3
    = t('image.new.add_image')
  = render 'form'
  = link_to 'Back', words_path

app/views/images/show.html.haml
%p
= @image.word.wordform
= @image.revision
= image_tag(@image.attachment, width: 200) if @image.attachment.attached?
= link_to 'Back', words_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ActiveStorageS3Uploader
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
  %body
    = yield

app/views/videos/_form.html.haml
= form_for [@word, @word.videos.build] do |form|
  %p.text-left.h5
    = form.file_field :attachment
    = form.hidden_field :attachment_cache
  .actions
    = form.submit

app/views/videos/index.html.haml
%h1 Images
%table
  %thead
    %tr
      %th video
    %tbody
    - @videos.each do |video|
      %tr
      %td= video_tag video.attachment
      %td= video.word.wordform
      %td= video.revision
%br/
= link_to "New Video", word_videos_path

app/views/videos/new.html.haml
%section
  %h3
    = t('video.new.add_video')
  = render 'form'
  = link_to 'Back', words_path

app/views/videos/show.html.haml
%p
= @video.word.wordform
= @video.revision
= video_tag(@video.attachment, width: 200) if @video.attachment.attached?
= link_to 'Back', words_path

app/views/words/_form.html.haml
= form_with(model: word, local: true) do |form|
  - if word.errors.any?
    #error_explanation
      %h2
        = pluralize(word.errors.count, "error")
        prohibited this word from being
        saved:
      %ul
        - word.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :wordform
    = form.text_field :wordform
  .actions
    = form.submit

app/views/words/edit.html.haml
%h1 Editing Word
= render "form", word: @word
= link_to "Show", @word
|
= link_to "Back", words_path

app/views/words/index.html.haml
%h1 Words
%table
  %thead
    %tr
      %th Word
  %tbody
    - @words.each do |word|
      %tr
        %td= word.wordform
        %td= link_to "Show", word
        %td= link_to "Edit", edit_word_path(word)
        %td= link_to "Destroy", word, method: :delete, data: { confirm: "Are you sure?" }
%br/
= link_to "New Word", new_word_path

app/views/words/new.html.haml
= form_with model: @word, local: true do |form|
  = form.label :wordform
  = form.text_field :wordform

app/views/words/show.html.haml
%p
  %strong Word:
  = @word.wordform
= link_to 'Edit', edit_word_path(@word)
|
= link_to 'Back', words_path